services:
  backend:
    build:
      context: .
    container_name: leaderapp
    ports:
      - "8000:8000"
    depends_on:
      - redis
    
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    

  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"

    