# Generated by Django 4.2.18 on 2025-01-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamesmodel",
            name="user",
        ),
    ]
